warehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: WWYOANN-WV28932
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      role: accountadmin
      database: dvd_rental_cdc
      warehouse: xsmall_wh
      schema: dev
      threads: 4
      client_session_keep_alive: False
    prod:
      type: snowflake
      account: WWYOANN-WV28932
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      role: accountadmin
      database: dvd_rental_cdc
      warehouse: xsmall_wh
      schema: prod
      threads: 12
      client_session_keep_alive: False
